"""Adiciona campo temporario ao modelo Cliente

Revision ID: c021f727c2ed
Revises: 3138fe43789d
Create Date: 2025-04-30 21:20:42.960519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c021f727c2ed'
down_revision = '3138fe43789d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporario', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('temporario')

    # ### end Alembic commands ###
